# Generated by Django 5.2.14 on 2026-05-19 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("codigo", models.CharField(max_length=7, unique=True)),
                ("descripcion", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Centro de costo",
                "verbose_name_plural": "Centros de costo",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CierrePeriodoContable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cod_comprob", models.CharField(max_length=7)),
                ("num_comprob", models.IntegerField()),
                ("item_comprob", models.SmallIntegerField(blank=True, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("cuenta", models.CharField(max_length=10)),
                ("doc_ref", models.CharField(blank=True, max_length=8)),
                ("observacion", models.CharField(blank=True, max_length=100)),
                (
                    "base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("cedula", models.CharField(blank=True, max_length=12)),
                ("centro_costo", models.CharField(blank=True, max_length=7)),
                (
                    "vr_debitos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "vr_creditos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de período",
                "verbose_name_plural": "Cierres de período",
            },
        ),
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("codigo", models.CharField(max_length=7, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=100)),
                ("ruta_imagen", models.TextField(blank=True)),
                ("regimen", models.CharField(blank=True, max_length=80)),
                ("resolucion", models.CharField(blank=True, max_length=15)),
                ("rango_desde", models.IntegerField(blank=True, null=True)),
                ("rango_hasta", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("ica", models.CharField(blank=True, max_length=80)),
                ("numero_inicial", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("observaciones1", models.TextField(blank=True)),
                ("observaciones2", models.TextField(blank=True)),
                ("observaciones3", models.TextField(blank=True)),
                ("ultimo_numero", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo",
                    models.CharField(max_length=12, unique=True, verbose_name="Código"),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("nivel", models.CharField(blank=True, max_length=1)),
                (
                    "naturaleza",
                    models.CharField(
                        blank=True,
                        choices=[("D", "Débito"), ("C", "Crédito")],
                        max_length=1,
                    ),
                ),
                (
                    "tipo_pgmd",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Patrimonial"),
                            ("G", "Gasto"),
                            ("M", "Movimiento"),
                            ("D", "Disponible"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "clase_apt",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Activo"), ("P", "Pasivo"), ("T", "Terceros")],
                        max_length=1,
                    ),
                ),
                ("captura_np", models.CharField(blank=True, max_length=1)),
                ("conversion", models.CharField(blank=True, max_length=5)),
                (
                    "base_ret",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "porc_ret",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("es_detalle", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("permite_cc", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Cuentas contables",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="DetallePlantilla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.SmallIntegerField()),
                ("cuenta", models.CharField(blank=True, max_length=10)),
                ("doc_ref", models.CharField(blank=True, max_length=8)),
                ("observacion", models.CharField(blank=True, max_length=200)),
                ("tipo_mov", models.CharField(blank=True, max_length=1)),
                ("valor", models.CharField(blank=True, max_length=32)),
                ("base", models.CharField(blank=True, max_length=32)),
                ("cedula", models.CharField(blank=True, max_length=12)),
                ("centro_costo", models.CharField(blank=True, max_length=7)),
                ("comentarios", models.CharField(blank=True, max_length=200)),
                ("doc_soporte", models.CharField(blank=True, max_length=15)),
            ],
            options={
                "ordering": ["item"],
            },
        ),
        migrations.CreateModel(
            name="MoviContCabecera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("num_comprob", models.IntegerField()),
                ("fecha", models.DateField(db_index=True)),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("doc_ref", models.CharField(blank=True, max_length=14)),
                ("doc_soporte", models.CharField(blank=True, max_length=15)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("B", "Borrador"),
                            ("C", "Contabilizado"),
                            ("A", "Anulado"),
                            ("R", "Revertido"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("es_reversa", models.BooleanField(default=False)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Asiento contable",
                "verbose_name_plural": "Asientos contables",
                "ordering": ["-fecha", "-num_comprob"],
            },
        ),
        migrations.CreateModel(
            name="MoviContLinea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("item_comprob", models.SmallIntegerField()),
                ("fecha", models.DateField(blank=True, null=True)),
                ("doc_ref", models.CharField(blank=True, max_length=14)),
                ("observacion", models.CharField(blank=True, max_length=200)),
                (
                    "base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "vr_debitos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vr_creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("doc_soporte", models.CharField(blank=True, max_length=15)),
            ],
            options={
                "verbose_name": "Línea de movimiento",
                "verbose_name_plural": "Líneas de movimiento",
                "ordering": ["item_comprob"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoContable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("anio", models.PositiveSmallIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                ("nombre", models.CharField(blank=True, max_length=30)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Abierto"),
                            ("C", "En cierre"),
                            ("X", "Cerrado"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("notas_cierre", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Período contable",
                "verbose_name_plural": "Períodos contables",
                "ordering": ["anio", "mes"],
            },
        ),
        migrations.CreateModel(
            name="PlantillaContable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cod_plantilla", models.CharField(max_length=7, unique=True)),
                ("nombre", models.CharField(max_length=60)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["cod_plantilla"],
            },
        ),
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cedula", models.CharField(max_length=12, unique=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NI", "NIT"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PP", "Pasaporte"),
                            ("RC", "Registro Civil"),
                        ],
                        default="CC",
                        max_length=2,
                    ),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        blank=True,
                        choices=[("N", "Natural"), ("J", "Jurídica")],
                        max_length=1,
                    ),
                ),
                ("nombre1", models.CharField(blank=True, max_length=50)),
                ("nombre2", models.CharField(blank=True, max_length=50)),
                ("apellido1", models.CharField(blank=True, max_length=50)),
                ("apellido2", models.CharField(blank=True, max_length=50)),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("barrio", models.CharField(blank=True, max_length=50)),
                ("municipio", models.CharField(blank=True, max_length=3)),
                ("departamento", models.CharField(blank=True, max_length=2)),
                ("distrito", models.CharField(blank=True, max_length=2)),
                ("telefono1", models.CharField(blank=True, max_length=30)),
                ("telefono2", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=80)),
                ("lugar_exp_cedula", models.CharField(blank=True, max_length=60)),
                ("fecha_exp_cedula", models.DateField(blank=True, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("lugar_nacimiento", models.CharField(blank=True, max_length=100)),
                ("sexo", models.CharField(blank=True, max_length=1)),
                ("tipo_sangre", models.CharField(blank=True, max_length=3)),
                ("parametros", models.CharField(blank=True, max_length=30)),
                ("comentarios", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tercero",
                "verbose_name_plural": "Terceros",
                "ordering": ["apellido1", "nombre1", "razon_social"],
            },
        ),
    ]
