# Generated by Django 5.2.14 on 2026-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounting', '0002_simplificar_comprobante'),
    ]

    operations = [
    ]
