# Generated by Django 5.2.14 on 2026-09-22 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_delete_movicontcabecera_linea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cuenta',
            name='accounting__nivel_4ee8e8_idx',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='clase_apt',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='clase_aptig',
            field=models.CharField(blank=True, db_column='clase_apt', max_length=1),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='naturaleza',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_pgmd',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='movicont',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movicont',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movicont',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
