# Generated by Django 5.2.14 on 2026-09-23 14:07

from django.db import migrations


def _clase(codigo: str) -> str:
    mapa = {'1': 'A', '2': 'P', '3': 'T', '4': 'I', '5': 'G'}
    return mapa.get(codigo[:1], '') if codigo else ''


def backfill_clase_aptig(apps, schema_editor):
    Cuenta = apps.get_model('accounting', 'Cuenta')
    for obj in Cuenta.objects.all():
        clase = _clase(obj.codigo)
        if obj.clase_aptig != clase:
            obj.clase_aptig = clase
            obj.save(update_fields=['clase_aptig'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_cuenta_accounting__nivel_4ee8e8_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_clase_aptig, migrations.RunPython.noop),
    ]