# Generated by Django 5.2.14 on 2026-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_data_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='frase_verificacion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
