# Generated by Django 5.2.14 on 2026-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_fecha_nacimiento_user_frase_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='controles',
            field=models.JSONField(blank=True, default=dict, help_text="Ej: {'editar_movimiento': 'P'|'D'}"),
        ),
    ]
