# Generated by Django 5.2.14 on 2026-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backfill_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='NameRole',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
