# Generated by Django 5.2.14 on 2026-05-19 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=20)),
                ("resource", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=100)),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("endpoint", models.CharField(blank=True, max_length=300)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
