# Generated by Django 5.2.14 on 2026-05-19 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConciliacionBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fecha_extracto", models.DateField()),
                (
                    "saldo_extracto",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("saldo_libros", models.DecimalField(decimal_places=2, max_digits=18)),
                ("diferencia", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "estado",
                    models.CharField(
                        choices=[("A", "Abierta"), ("C", "Cerrada")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=200)),
                ("banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=50, unique=True)),
                ("tipo", models.CharField(blank=True, max_length=30)),
                ("moneda", models.CharField(default="COP", max_length=3)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("fecha_apertura", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("swift", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fecha", models.DateField(db_index=True)),
                ("descripcion", models.CharField(max_length=300)),
                ("referencia", models.CharField(blank=True, max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("D", "Débito"), ("C", "Crédito")], max_length=1
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("P", "Pendiente"), ("C", "Conciliado")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("origen", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
